name: TheSecretTrails
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-sitemap
baseurl: ""
url: https://thesecrettrails.com/
include: ["_pages"]
permalink: /:title/
permalink: /404.html
